version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/tmp

    steps:
      - checkout

      - run:
          name: Install dependencies
          working_directory: /
          command: |
            sudo apt-get -y -qq update
            sudo apt-get -y -qq install python-pip python-dev
            pip install awscli --upgrade --user

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn build
      - store_artifacts:
          path: ~/tmp/build
      - deploy:
          name: Deploy to s3
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              PATH=~/.local/bin:$PATH .circleci/deploy.sh "./build" "congresswhois.com"
            fi
